# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
xcode_workspace: Example/RKPieChart.xcworkspace
xcode_sdk: iphonesimulator10.0
xcode_scheme: RKPieChartExample
podfile: Example/Podfile
on:
  repo: ridvank/RKPieChart
  tags: true
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild -version
